/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jbailey' at '4/6/16 11:15 AM' with Gradle 2.9
 *
 * @author jbailey, @date 4/6/16 11:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
